# Generated by Django 3.1.2 on 2020-10-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='smtpemail',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
